language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install
  - pear install PHP_CodeSniffer
  - phpenv rehash

script: 
  - phpcs --standard=psr2 src
  - php test/run-tests.php
