language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

install:
  - composer install
  - pear install PHP_CodeSniffer
  - phpenv rehash

script: 
  - phpcs --runtime-set ignore_warnings_on_exit true --standard=psr2 src
  - php test/run-tests.php
